var mt_lib = [
	{ w: "Hello", r: "Bello" },
	{ w: "Apel", r: "Papples" },
	{ w: "Es Krim", r: "Gelato" },
	{ w: "Kamu", r: "tu" },
	{ w: "Lapar", r: "Banananaah" },
	{ w: "Apa", r: "Po-ka" },
	{ w: "1", r: "na" },
	{ w: "2", r: "tu" },
	{ w: "3", r: "Sae" },
	{ w: "4", r: "Po" },
	{ w: "5", r: "Pa" },
	{ w: "6", r: "Ti" },
	{ w: "7", r: "Ben" },
	{ w: "8", r: "Pi" },
	{ w: "Makan", r: "Matoka" }, 
	{ w: "Cheers", r: "Kampai" },
	{ w: "Kursi", r: "Chasy" },
	{ w: "Bawah", r: "Buttom" },
	{ w: "Cium", r: "Muak" },
	{ w: "Mainan", r: "Papoi" },
	{ w: "Nikah", r: "La Boda" },
	{ w: "Selamat Tinggal", r: "Poopaye" },
	{ w: "Jani", r: "Underwear" },
	{ w: "Kami Cinta kamu", r: "Tulaliloo ti amo"},
	{ w: "Aku Benci Kamu", r: "Tatata bala tu" },
	{ w: "Lihat Dirimu", r: "Luk at tu"},
	{ w: "Jelek", r: "Bananoninna" },
	{ w: "Anak Kecil", r: "Boca" },
	{ w: "Api", r: "Beedoobeedoobeeboo"},
	{ w: "Aku Raja Dunia", r: "Super Pokalilomataaaa"},
	{ w: "Untuk Kamu", r: "Para Tu" },
	{ w: "Terima Kasih", r: "Tank yu"},
	{ w: "Sayang", r: "Widya" },
	{ w: "Minum", r: "nono" },
];

	
